### PR TITLE
<FIX> Typos and Grammatical errors

### LINKED ISSUE #7: <FIX> fix typing and grammatical errors in README.md
Screenshot from 2023-10-27 19-27-23
Assign me this issue as I'm trying for hacktoberfest and will be a good start for me.

### PR DESCRIPTION
**Pull request by rover07**
closes #7 
- This PR fixes all the typos and grammatical errors in the README.md file making the markdown more professional.

### CODE REVIEW

**Comment by iamwatchdogs** [comment]
@rover07 Appreciate your help, can you take a look at the other files too ???...

**Comment by rover07** [comment]
Sure! Should I raise a new PR for that or commit to the current branch? @iamwatchdogs 
Also, the hacktoberfest tag will be grateful.

**Comment by iamwatchdogs** [comment]
@rover07 Please commit your changes to the current branch/PR and make sure to rename the PR to **Typos and Grammatical errors** instead of only for the `README.md` file.

**Comment by rover07** [comment]
We are good to go @iamwatchdogs .

**Review by iamwatchdogs — COMMENTED** [review]
Review and Approved by @iamwatchdogs

**Comment by iamwatchdogs** [comment]
Thank you for contributing @rover07.

**Pull request merged**
